version: "3.9"

services:
  backend:
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_CELERY_BROKER_URL: ${APP_CELERY_BROKER_URL:-memory://}
      APP_CELERY_RESULT_BACKEND: ${APP_CELERY_RESULT_BACKEND:-cache+memory://}
      APP_QUEUE_FALLBACK_ENABLED: ${APP_QUEUE_FALLBACK_ENABLED:-true}

  worker:
    depends_on:
      backend:
        condition: service_healthy
    environment:
      APP_CELERY_BROKER_URL: ${APP_CELERY_BROKER_URL:-memory://}
      APP_CELERY_RESULT_BACKEND: ${APP_CELERY_RESULT_BACKEND:-cache+memory://}
      APP_QUEUE_FALLBACK_ENABLED: ${APP_QUEUE_FALLBACK_ENABLED:-true}

  beat:
    depends_on:
      backend:
        condition: service_healthy
    environment:
      APP_CELERY_BROKER_URL: ${APP_CELERY_BROKER_URL:-memory://}
      APP_CELERY_RESULT_BACKEND: ${APP_CELERY_RESULT_BACKEND:-cache+memory://}
      APP_QUEUE_FALLBACK_ENABLED: ${APP_QUEUE_FALLBACK_ENABLED:-true}

  redis:
    profiles:
      - redis
