version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["php", "-S", "0.0.0.0:80", "-t", "public"]
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      DEV_MODE: "true"
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    environment:
      MINIO_ADDRESS: ":9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
