line-length = 88
target-version = "py311"

[lint]
select = ["E", "F", "B"]
ignore = ["E501"]
exclude = ["app/models/generated.py", "app/schemas/generated.py"]

[lint.isort]
known-first-party = ["app"]
