%% API Surface
graph LR
  api_root[API Root]
  api_root --> api_projects[projects (47)]
  api_root --> api_instances[instances (37)]
  api_root --> api_account[account (23)]
  api_root --> api_assets[assets (19)]
  api_root --> api_maintenance[maintenance (16)]
  api_root --> api_cms[cms (7)]
  api_root --> api_file[file (6)]
  api_root --> api_groups[groups (6)]
  api_root --> api_categories[categories (5)]
  api_root --> api_login[login (5)]
  api_root --> api_modules[modules (5)]
  api_root --> api_clients[clients (4)]
  api_root --> api_locations[locations (4)]
  api_root --> api_s3files[s3files (4)]
  api_root --> api_notifications[notifications (3)]
  api_root --> api_permissions[permissions (3)]
  api_root --> api_training[training (3)]
  api_root --> api_manufacturer[manufacturer (2)]
  api_root --> api_apiHead[apiHead (1)]
  api_root --> api_apiHeadSecure[apiHeadSecure (1)]
  api_root --> api_barcodes[barcodes (1)]
  api_root --> api_icons[icons (1)]
  api_root --> api_onlineCheck[onlineCheck (1)]
  api_root --> api_openApiYAMLHeaders[openApiYAMLHeaders (1)]
  api_root --> api_search[search (1)]
  api_root --> api_server[server (1)]
