name: Feature request
description: Suggest an enhancement or new capability
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please help us understand the problem and the desired outcome.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One sentence describing the feature.
      placeholder: Add support for ...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem or workflow does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how the feature should work, including UI or API changes.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other approaches?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mock-ups, references, or any extra notes.
