name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch:

jobs:
  lint:
    name: Run frontend checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend && npm install
          else
            echo 'No frontend package.json found, skipping install'
          fi
      - name: Lint placeholder
        run: echo 'Frontend lint placeholder'
